# -- values shared globally between chart and subcharts (use this part is you include subchart which need information from the parent chart)
global:
  imagePullSecrets: ""
  # -- set global image parameters
  image:
    # -- set global image registry
    registry: ""
    # -- set global image pullPolicy
    imagePullPolicy: ""
  # -- set global revision history limit
  revisionHistoryLimit: 10
  # -- Default priority class for all components
  priorityClassName: ""
  # -- Default node selector for all components
  nodeSelector: {}
  # -- Default tolerations for all components
  tolerations: []
  # -- Deployment strategy for the all deployed Deployments
  deploymentStrategy: {}
    # type: RollingUpdate
    # rollingUpdate:
    #   maxSurge: 25%
    #   maxUnavailable: 25%
  # -- Annotations for the all deployed Deployments
  deployAnnotations: {}
  # -- Labels for all pods
  podLabels: {}
  # -- the global configuration of the usage of Stakater reloader
  stakater:
    # -- enabled stakater usage
    enabled: false
    # -- enabled auto mode
    auto: false

# Default values for demo-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

test:
  enabled: true

replicaCount: 1

image:
  registry: docker.io
  repository: ixxel/demo-web
  pullPolicy: Always
  tag: latest
  digest: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

automountServiceAccountToken: false 
# -- the name of the service account used to access the API server
serviceAccount:
  create: true
  annotations: {}
  labels: {}
  name: ""

podAnnotations: {}

deployAnnotations: {}

podLabels: {}

deploymentStrategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 25%
  #   maxUnavailable: 25%

podSecurityContext:
  enabled: false
  seccompProfile:
    type: RuntimeDefault
  # runAsUser: 10000
  # runAsGroup: 10000
  # fsGroup: 10000
# -- Toggle and define Back container-level security context
containerSecurityContext:
  enabled: false
  # runAsNonRoot: true
  # readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
    - ALL
    - NET_RAW
    add:
    - CHOWN

service:
  annotations: {}
  labels: {}
  type: ClusterIP
  servicePortName: http
  port: 80
  targetPort: 8080
  nodePort: 30080
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalIPs: []
  externalTrafficPolicy: ""
  sessionAffinity: ""

rollouts:
  enabled: false
  workloadRef:
    scaleDown: progressively

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

gatewayApi:
  enabled: false
  annotations: {}
  gateway:
    name: ""
    namespace: ""
    section: ""
  httpRoute:
    hosts:
    - example.com
    pathType: PathPrefix
    path: /

startupProbe:
  enabled: false
  path: /management/health/liveness
  initialDelaySeconds: 0
  periodSeconds: 3
  failureThreshold: 20
  timeoutSeconds: 1

# See kubernetes documentation for more information about probes:
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
livenessProbe:
  enabled: false
  path: /management/health/liveness
  initialDelaySeconds: 0
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 1

# See kubernetes documentation for more information about probes:
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
readinessProbe:
  enabled: false
  path: /management/health/readiness
  initialDelaySeconds: 0
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  # targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 150
  scaleUpPolicies:
  - type: Pods
    value: 1
    periodSeconds: 60
  scaleDownPolicies:
  - type: Pods
    value: 2
    periodSeconds: 60
  - type: Percent
    value: 50
    periodSeconds: 60

nodeSelector: {}

tolerations: []

affinity: {}
