{{- if .Values.autoscaling.enabled }}
apiVersion: {{ include "common.capabilities.hpa.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "demo-web.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "demo-web.fullname" . }}
  minReplicas: {{ default 2 .Values.autoscaling.minReplicas }}
  maxReplicas: {{ default 5 .Values.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if eq (include "common.capabilities.hpa.apiVersion" $) "autoscaling/v2beta1" }}
        targetAverageUtilization: {{ . }}
        {{- else }}
        target:
          averageUtilization: {{ . }}
          type: Utilization
        {{- end }}
  {{- end }}
  {{- with .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if eq (include "common.capabilities.hpa.apiVersion" $) "autoscaling/v2beta1" }}
        targetAverageUtilization: {{ . }}
        {{- else }}
        target:
          averageUtilization: {{ . }}
          type: Utilization
        {{- end }}
  {{- end }}
  behavior:
    {{- with .Values.autoscaling.scaleUpPolicies }}
    scaleUp:
      policies:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.autoscaling.scaleDownPolicies }}
    scaleDown:
      policies:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}