{{- if .Values.gatewayApi.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "demo-web.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io	
    kind: Gateway
    name: {{- .Values.gatewayApi.gateway.name }}
    namespace: {{- .Values.gatewayApi.gateway.namespace }}
    sectionName: {{- .Values.gatewayApi.gateway.section }}
  hostnames:
  {{- range .Values.gatewayApi.httpRoute.hosts }}
  - {{ . | quote }}
  {{- end }}
  rules:
  - backendRefs:
      - group: ''
        kind: Service
        name: {{ include "demo-web.fullname" . }}
        port: {{ .Values.service.port }}
        weight: 100
    matches:
      - path:
          type: {{ .Values.gatewayApi.httpRoute.pathType }}
          value: {{ .Values.gatewayApi.httpRoute.path }}
{{- end }}