{{- if .Values.rollouts.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "demo-web.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  analysis:
    successfulRunHistoryLimit: 10
    unsuccessfulRunHistoryLimit: 10
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" ( list .Values.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "demo-web.fullname" . }}
  strategy:
    canary:
      canaryService: {{ include "demo-web.fullname" . }}-preview
      stableService: {{ include "demo-web.fullname" . }}-stable
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: {{ include "demo-web.fullname" . }}
            namespace: {{ .Release.Namespace | quote }}
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 100
      - pause: {}
  revisionHistoryLimit: 2
{{- end }}