{{- if .Values.rollouts.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-web.fullname" . }}-preview
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
{{- if .Values.service.labels }}
{{- toYaml .Values.service.labels | nindent 4 }}
{{- end }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
  - name: {{ default "http" .Values.service.servicePortName }}
    port: {{ default 80 .Values.service.port }}
    targetPort: {{ default 8080 .Values.service.targetPort }}
    protocol: TCP
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" ( list .Values.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
{{- if eq .Values.service.type "LoadBalancer" }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs: {{ .Values.service.externalIPs }}
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
{{- end }}
{{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
{{- end }}
{{- end -}}
{{- end }}