---
name: Helm AIO build
on:
  push:
    branches:
      - "main"
    paths:
      - "aio/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
    paths:
      - "aio/**"
  workflow_dispatch:
jobs:
  aio-helm-build:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/helm-build.yaml@main
    with:
      workingdir: aio
      auto-update-chart: "true"
      auto-tag-repo: "true"
      helm-values-file-test: values.yaml
    secrets:
      GHA_TOKEN: ${{ secrets.PAT }}
      GHA_PERSONNAL_ADMIN_TOKEN: ${{ secrets.PAT }}
      CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}