---
name: Helm demo-web build
on:
  push:
    branches:
      - "main"
    paths:
      - "demo-web/**"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "main"
    paths:
      - "demo-web/**"
  workflow_dispatch:
jobs:
  demo-web-helm-build:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/helm-build.yaml@main
    with:
      workingdir: demo-web
      auto-update-chart: "true"
      auto-tag-repo: "true"
      helm-values-file-test: values.yaml
      helm-strict: false
    secrets:
      GHA_TOKEN: ${{ secrets.PAT }}
      GHA_PERSONNAL_ADMIN_TOKEN: ${{ secrets.SUPER_ADMIN_TOKEN }}
      CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}